# Generated by Django 2.2.6 on 2019-11-15 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post3',
            name='end_date_score',
        ),
        migrations.RemoveField(
            model_name='post3',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='post3',
            name='start_date',
        ),
        migrations.CreateModel(
            name='Post6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('total_score', models.CharField(max_length=100)),
                ('exam_name', models.TextField()),
                ('subject_name', models.TextField()),
                ('questions', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
